export const MODAL_OPEN = "MODAL_OPEN"


//#region 		ROOM

export const ROOM_SELECTED = "ROOM_SELECTED"

export const ROOM_FETCH_REQUESTED = "ROOM_FETCH_REQUESTED"
export const ROOM_FETCH_SUCCEEDED = "ROOM_FETCH_SUCCEEDED"
export const ROOM_FETCH_FAILED = "ROOM_FETCH_FAILED"

export const ROOM_ADD_REQUESTED = "ROOM_ADD_REQUESTED"
export const ROOM_ADD_SUCCEEDED = "ROOM_ADD_SUCCEEDED"
export const ROOM_ADD_FAILED = "ROOM_ADD_FAILED"

export const ROOM_UPDATE_REQUESTED = "ROOM_UPDATE_REQUESTED"
export const ROOM_UPDATE_SUCCEEDED = "ROOM_UPDATE_SUCCEEDED"
export const ROOM_UPDATE_FAILED = "ROOM_UPDATE_FAILED"

export const ROOM_DELETE_REQUESTED = "ROOM_DELETE_REQUESTED"
export const ROOM_DELETE_SUCCEEDED = "ROOM_DELETE_SUCCEEDED"
export const ROOM_DELETE_FAILED = "ROOM_DELETE_FAILED"

//#endregion 		ROOM

//#region 		EMPLOYE		

export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED"

export const EMPLOYEE_FETCH_REQUESTED = "EMPLOYEE_FETCH_REQUESTED"
export const EMPLOYEE_FETCH_SUCCEEDED = "EMPLOYEE_FETCH_SUCCEEDED"
export const EMPLOYEE_FETCH_FAILED = "EMPLOYEE_FETCH_FAILED"

export const EMPLOYEE_ADD_REQUESTED = "EMPLOYEE_ADD_REQUESTED"
export const EMPLOYEE_ADD_SUCCEEDED = "EMPLOYEE_ADD_SUCCEEDED"
export const EMPLOYEE_ADD_FAILED = "EMPLOYEE_ADD_FAILED"

export const EMPLOYEE_UPDATE_REQUESTED = "EMPLOYEE_UPDATE_REQUESTED"
export const EMPLOYEE_UPDATE_SUCCEEDED = "EMPLOYEE_UPDATE_SUCCEEDED"
export const EMPLOYEE_UPDATE_FAILED = "EMPLOYEE_UPDATE_FAILED"

export const EMPLOYEE_DELETE_REQUESTED = "EMPLOYEE_DELETE_REQUESTED"
export const EMPLOYEE_DELETE_SUCCEEDED = "EMPLOYEE_DELETE_SUCCEEDED"
export const EMPLOYEE_DELETE_FAILED = "EMPLOYEE_DELETE_FAILED"

//#endregion 		EMPLOYE